version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Etc/UTC"
      time: "03:00"
    pull-request-branch-name:
      separator: "-"
